[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=65", "wheel"]

[project]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: Apache Software License",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Scientific/Engineering"
]
dependencies = ["pyyaml"]
description = "Date and time manipulation routines for the use of weather data"
dynamic = ["version"]
license = {file = "LICENSE"}
name = "earthkit-time"
readme = "README.md"
requires-python = ">= 3.8"

[project.optional-dependencies]
docs = [
  "myst-parser",
  "Sphinx",
  "sphinx-rtd-theme"
]
test = [
  "pytest >= 8.1"
]

[project.scripts]
earthkit-climdates = "earthkit.time.cli.climatology:main"
earthkit-date = "earthkit.time.cli.date:main"
earthkit-dateseq = "earthkit.time.cli.sequence:main"
earthkit-datetime = "earthkit.time.cli.datetime:main"

[project.urls]
Documentation = "https://earthkit-time.readthedocs.io"
Homepage = "https://github.com/ecmwf/earthkit-time/"

[tool.pytest.ini_options]
addopts = "--doctest-modules"
minversion = "8.1"
testpaths = [
  "tests"
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = [
  "D1",  # pydocstyle: Missing Docstrings
  "D107",  # pydocstyle: numpy convention
  "D203",
  "D205",
  "D212",
  "D213",
  "D401",
  "D402",
  "D413",
  "D415",
  "D416",
  "D417"
]
select = [
  "F",  # pyflakes
  "E",  # pycodestyle
  "W",  # pycodestyle warnings
  "I",  # isort
  "D"  # pydocstyle
]

[tool.setuptools.dynamic]
version = {attr = "earthkit.time.__version__"}

[tool.setuptools.package-data]
"earthkit.time.data" = ["*/*.yaml"]

[tool.setuptools.packages.find]
where = ["src"]
